# Generated by Django 4.1 on 2022-08-21 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_search_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Searches'},
        ),
    ]
